# Generated by Django 4.2.3 on 2023-09-25 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Business", "Business"),
                            ("Student", "Student"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="profile_image")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Addbook_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=50, verbose_name="name")),
                ("title", models.CharField(max_length=225)),
                ("subtitle", models.CharField(max_length=225)),
                ("authors", models.CharField(max_length=225)),
                ("publisher", models.CharField(max_length=225)),
                (
                    "Date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="published_date"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Business Analytics", "Business Analytics"),
                            ("deep learning", "deep learning"),
                            ("data science", "data science"),
                            ("maths", "maths"),
                            ("Data ethics", "Data ethics"),
                            ("NLP", "NLP"),
                            ("python", "python"),
                            ("R Studio", "R Studio"),
                            ("SQL", "SQL"),
                            ("visualization", "visualization"),
                            ("statistics", "statistics"),
                            ("Other", "Others"),
                        ],
                        default="Others",
                        max_length=30,
                    ),
                ),
                (
                    "distribution_expense",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
